# Generated by Django 2.2.12 on 2022-12-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('rating', models.CharField(choices=[('E', 'E'), ('T', 'T'), ('M', 'M')], default='E', max_length=25)),
                ('genre', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
