# Generated by Django 2.2.12 on 2022-12-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(verbose_name='Date Played'),
        ),
        migrations.AlterField(
            model_name='session',
            name='length',
            field=models.DurationField(),
        ),
    ]
