# Generated by Django 2.2.12 on 2022-12-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20221220_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='length',
            field=models.CharField(max_length=20),
        ),
    ]
