# Generated by Django 2.2.12 on 2022-12-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='characters',
            field=models.ManyToManyField(to='main_app.Character'),
        ),
    ]
